Created a style guide and refactored code to follow style guide
Three0Dev/Three0 pull request #17
Opened 2022-10-12 20:30 UTC by srawulwar

2022-10-13 22:12 UTC, techster10173 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add style guide to Three0Core](https://trello.com/c/7qLaZBiK/15-add-style-guide-to-three0core)

2022-10-17 16:04 UTC, techster10173 requested changes

2022-10-25 00:45 UTC, techster10173 approved these changes
LGTM! Just double check to make sure that the style guide, eslint/prettier, and everything is matching and we can merge

2022-10-26 19:07 UTC, dhruvarao11 approved these changes
LGTM

2022-10-26 20:02 UTC, merged