deleting project reference when project is DNE
Three0Dev/Three0 pull request #32
Opened 2022-11-04 00:16 UTC by sparshypop7

plz

2022-11-04 00:21 UTC, techster10173 requested changes
Fix up the suggested comments before PR can be approved

2022-11-04 00:21 UTC, techster10173 commented on contract/controller/src/lib.rs
> +        };
Remove the semicolon

2022-11-04 00:21 UTC, techster10173 commented on src/views/Dash.tsx
> +  function validityCheck(isValid: boolean) {
Make this an async function...remove the many `.then`'s and use `await` instead.

2022-11-04 04:19 UTC, techster10173 requested changes

2022-11-04 04:19 UTC, techster10173 commented on src/views/Dash.tsx
> +      await window.contract.delete_project({
Don't use `.catch` wrap it in a try-catch and handle the error in the catch section

2022-11-04 22:07 UTC, techster10173 requested changes

2022-11-04 22:07 UTC, techster10173 commented on src/views/Dash.tsx
> +      Swal.fire({
Put the Swal inside of the `try` block. The code here will always be called regardless of if there is an error or not

2022-11-04 23:12 UTC, techster10173 approved these changes
LGTM!

2022-11-06 21:27 UTC, srawulwar approved these changes
need to follow style guide, rest looks good

2022-11-07 02:15 UTC, merged