Checking validity of Project Name
Three0Dev/Three0 pull request #35
Opened 2022-11-10 22:58 UTC by sparshypop7

2022-11-11 01:06 UTC, techster10173 requested changes
Make sure you merge main into this

2022-11-11 01:06 UTC, techster10173 commented on src/views/ProjectsDash.tsx
> +          for(let i=0; i<arr_phrases.length; i++) {
See if you want to replace the for-loop with this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes or if you want index try using `indexOf()`

2022-11-11 01:06 UTC, techster10173 commented on src/views/ProjectsDash.tsx
> +        } else if (pid.length > 64) {
Change length tolerance to include sub accounts for hosting/storage

2022-11-11 01:06 UTC, techster10173 commented on src/views/ProjectsDash.tsx
> +        const arr_phrases = ["near", "wallet", "account", "contract", "app", "test", "dev", "mainnet", "testnet", "helper"];
Change variable name to INVALID_PHRASES or smth along those lines

2022-11-14 03:02 UTC, techster10173 approved these changes
LGTM!

2022-11-14 03:03 UTC, srawulwar approved these changes
lgtm

2022-11-14 03:08 UTC, merged